export const STORE_PAYMENT_SETTLEMENT_STATUS = {
  ACTIVA: 'ACTIVA',
  ANULADA: 'ANULADA',
} as const;

export const STORE_SETTLEMENT_ELIGIBLE_PAYMENT_METHODS = [
  'EFECTIVO_CONTRA_ENTREGA',
  'VISA_LINK_MANUAL',
  'TRANSFERENCIA_BANCARIA',
  'DEPOSITO_BANCARIO',
] as const;

export const STORE_SETTLEMENT_INCIDENT_REASONS = [
  'MONTO_NO_COINCIDE',
  'COMPROBANTE_INVALIDO',
  'REFERENCIA_DUPLICADA',
  'EFECTIVO_NO_ENTREGADO',
  'DIFERENCIA_CAJA',
  'OTRO',
] as const;
